**Уровень 0:** <br>
Создайте матрицу 3 на 3, заполненную числами от 1 до 9  <br>
Прибавьте к ней матрицу с единицами на диагонале   <br>
Умножьте полученную матрицу на вектор (1, 2, 3)   <br>
Посчитайте обратную матрицу к полученной матрице  <br>



In [2]:
import numpy as np

In [20]:
#Создайте матрицу 3 на 3, заполненную числами от 1 до 9 
m = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
one = np.eye(3)
v = np.array([1,2,3])

In [6]:
#Прибавьте к ней матрицу с единицами на диагонале 
m_plus_one = m + one
m_plus_one

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [19]:
#Умножьте полученную матрицу на вектор (1, 2, 3) 
m_new = m_plus_one @ v
m_new

array([15., 34., 53.])

In [9]:
# Посчитайте обратную матрицу к полученной матрице 

# А как можно найти обратную матрицу, если у нас после умножения остался только вектор? 
reverse_m = np.linalg.inv(m) 
reverse_m

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [21]:
# Обратная матрица к первоначальной матрице выглядит так
reverse_m = np.linalg.inv(m) 
reverse_m

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [28]:
from numpy.linalg import inv
reverse_m = inv(np.matrix(m))
reverse_m

matrix([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
        [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
        [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [29]:
m @ reverse_m

matrix([[ 0.,  0.,  0.],
        [-4.,  0., -4.],
        [ 0.,  0.,  0.]])

**Уровень 1:** <br>
Дан объект в 2d пространстве:
import numpy as np
import matplotlib.pyplot as plt

A = [  <br>
[-100, -100, 1],  <br>
[-100, 100, 1],  <br>
[100, 100, 1],  <br>
[0, 0, 1],  <br>
[100, -100, 1],  <br>
[-100, -100, 1]  <br>
]  <br>

A = np.array(A)  <br>
x = A[:,0]  <br>
y = A[:,1]  <br>
plt.plot(x, y)  <br>
plt.ylim([-200, 200])  <br>
plt.xlim([-200, 200]) <br> 

При помощи матричных операций выполните:  <br>
Уменьшить объект в два раза.  <br>
Повернуть на 130 градусов.  <br> 
Отразить объект относительно прямой y=x  <br>
Выполнить смещение объекта и масштабирование (применить 2 матрицы трансформаций). Смещение на (200, 300) и масштабирование на (0.5, 1,2)

(-200, 200)